List expr mr
whirlplatform/whirl pull request #62
Opened 2022-11-07 14:42 UTC by VladWick

2022-11-08 10:47 UTC, lichnost requested changes

2022-11-08 10:47 UTC, lichnost commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/driver/multibase/fetch/base/AbstractPlainDataFetcher.java
> +            int labelInd = reader.getFieldIndex(field.getLabelExpression());
От этого вроде бы избавлялись.

2022-11-08 10:47 UTC, lichnost commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/driver/multibase/fetch/base/AbstractPlainDataFetcher.java
> +            if (field.getType() == org.whirlplatform.meta.shared.data.DataType.LIST) {
Думаю здесь это условие надо вставить в if который выше:
field.getType() == org.whirlplatform.meta.shared.data.DataType.LIST && !StringUtils.isEmpty(field.getLabelExpression())

2022-11-08 10:47 UTC, lichnost commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/driver/multibase/fetch/base/PlainListFetcherHelper.java
> +        this.labelExpression = dbDatabase.getValueExpr(config.getLabelExpression(), DataType.UNKNOWN).as(metadata.getTitle() + "_list");
Из констант LABEL_EXPRESSION_NAME надо подставить.

2022-11-08 10:47 UTC, lichnost commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/driver/multibase/fetch/base/PlainTableFetcherHelper.java
> +            TableColumnElement nameColumn = table.getColumn(((TreeClassLoadConfig) loadConfig).getLabelExpression());
По загрузке TreeBuilder похоже, что не работает из-за этого.

2022-11-08 10:47 UTC, lichnost commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/driver/multibase/fetch/base/PlainTableFetcherHelper.java
> +                this.dbTable.addColumn(LABEL_EXPRESSION_NAME, DataType.TEXT, 0, DataMode.NotNull);
Здесь тоже что-то не доделано.

2022-11-08 10:47 UTC, lichnost commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/driver/multibase/fetch/base/PlainTableFetcherHelper.java
> +                col = this.dbTable.getColumn(filter.getMetadata().getLabelExpression());
Здесь тоже что-то не доделано.

2022-11-08 10:47 UTC, lichnost commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/expimp/CSVExporter.java
> +			result = reader.getString(reader.getFieldIndex(field.getLabelExpression()));
getFieldIndex на labelExpression не работает - в одном из мест уже выяснили.

2022-11-08 10:47 UTC, lichnost commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/expimp/Exporter.java
> +            object = reader.getString(reader.getFieldIndex(field.getLabelExpression()));
getFieldIndex на labelExpression не работает - в одном из мест уже выяснили.

2022-11-08 10:47 UTC, lichnost commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/driver/multibase/fetch/oracle/OraclePlainDataFetcher.java
> +            int labelInd = reader.getFieldIndex(field.getLabelExpression());
Здесь тоже что-то не доделано.

2022-11-08 10:47 UTC, lichnost commented on whirl-editor/whirl-editor-shared/src/main/resources/org/whirlplatform/editor/shared/i18n/EditorMessage_ru.properties
> +templ_success_save_with_name=Ð¨Ð°Ð±Ð»Ð¾Ð½ ÑÑÐ¿ÐµÑÐ½Ð¾ ÑÐ¾ÑÑÐ°Ð½ÐµÐ½ Ñ Ð¸Ð¼ÐµÐ½ÐµÐ¼
С кодировками что-то все-таки не то видимо. Надо протестировать на русской версии интерфейса и убедится что все что по-русски не сломалось.

2022-11-09 09:27 UTC, VladWick commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/driver/multibase/fetch/base/AbstractPlainDataFetcher.java
> +            if (field.getType() == org.whirlplatform.meta.shared.data.DataType.LIST) {
Весь этот блок сделал

2022-11-09 09:28 UTC, VladWick commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/driver/multibase/fetch/base/PlainTableFetcherHelper.java
> +            TableColumnElement nameColumn = table.getColumn(((TreeClassLoadConfig) loadConfig).getLabelExpression());
А что за алгоритм закоменченный? Или просто сделать формирование TreeClassConfig из TreeBuilder через лист ?

2022-11-09 09:31 UTC, VladWick commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/expimp/CSVExporter.java
> +			result = reader.getString(reader.getFieldIndex(field.getLabelExpression()));
Исправил

2022-11-09 09:31 UTC, VladWick commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/expimp/Exporter.java
> +            object = reader.getString(reader.getFieldIndex(field.getLabelExpression()));
Исправил

2022-11-09 09:31 UTC, VladWick commented on whirl-editor/whirl-editor-shared/src/main/resources/org/whirlplatform/editor/shared/i18n/EditorMessage_ru.properties
> +templ_success_save_with_name=Ð¨Ð°Ð±Ð»Ð¾Ð½ ÑÑÐ¿ÐµÑÐ½Ð¾ ÑÐ¾ÑÑÐ°Ð½ÐµÐ½ Ñ Ð¸Ð¼ÐµÐ½ÐµÐ¼
Это проблема скорее всего только с моей стороны, потому что даже доки в эдиторе у меня на русском языке отображаются крякозябрами

2022-11-09 09:32 UTC, VladWick commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/driver/multibase/fetch/oracle/OraclePlainDataFetcher.java
> +            int labelInd = reader.getFieldIndex(field.getLabelExpression());
Попробовал переделать field.getLabelExpression() в field.getName() + LABEL_EXPRESSION_NAME.

2022-11-09 09:35 UTC, VladWick commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/driver/multibase/fetch/base/PlainTableFetcherHelper.java
> +                col = this.dbTable.getColumn(filter.getMetadata().getLabelExpression());
Наверное, я не знаю что)))
Мы же в таблице, там где у нас тип FILE, ничего не делали...

2022-11-09 09:35 UTC, VladWick commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/driver/multibase/fetch/base/PlainTableFetcherHelper.java
> +                this.dbTable.addColumn(LABEL_EXPRESSION_NAME, DataType.TEXT, 0, DataMode.NotNull);
Тут вроде всё в порядке. Иначе без этой колонки не будет LIST колонка работать. Не будет создаваться колонка, к которой будет запрос labelExpression

2022-11-09 15:24 UTC, lichnost commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/driver/multibase/fetch/base/PlainTableFetcherHelper.java
> +                col = this.dbTable.getColumn(filter.getMetadata().getLabelExpression());
Да, верно по файлу ничего не делали.

2022-11-09 15:24 UTC, lichnost commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/driver/multibase/fetch/base/PlainTableFetcherHelper.java
> +                this.dbTable.addColumn(LABEL_EXPRESSION_NAME, DataType.TEXT, 0, DataMode.NotNull);
Это блок предположительно можно убрать совсем.

2022-11-09 15:24 UTC, lichnost commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/driver/multibase/fetch/oracle/OraclePlainDataFetcher.java
> +            int labelInd = reader.getFieldIndex(field.getLabelExpression());
Пока не трогаем.

2022-11-09 15:25 UTC, lichnost commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/driver/multibase/fetch/base/PlainTableFetcherHelper.java
> +            TableColumnElement nameColumn = table.getColumn(((TreeClassLoadConfig) loadConfig).getLabelExpression());
Отдельно будем по стилям проверять

2022-11-10 12:40 UTC, lichnost commented on whirl-editor/whirl-editor-shared/src/main/resources/org/whirlplatform/editor/shared/i18n/EditorMessage_ru.properties
> +templ_success_save_with_name=Ð¨Ð°Ð±Ð»Ð¾Ð½ ÑÑÐ¿ÐµÑÐ½Ð¾ ÑÐ¾ÑÑÐ°Ð½ÐµÐ½ Ñ Ð¸Ð¼ÐµÐ½ÐµÐ¼
Исправлено.

2022-11-10 12:41 UTC, lichnost approved these changes

2022-11-10 12:41 UTC, merged