logs
whirlplatform/whirl pull request #68
Opened 2022-11-21 14:07 UTC by VladWick

2022-11-22 03:25 UTC, lichnost commented
Файл whirl-editor/whirl-editor-server/propertieslogs.log надо убрать.

2022-11-22 03:26 UTC, lichnost requested changes

2022-11-22 03:26 UTC, lichnost commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/driver/multibase/fetch/base/BasePlainTableFetcher.java
> +        _log.info("Hello LOGS! ::: " + selectCmd.getSelect());
Вместо "Hello LOGS!" осмысленный текст нужен.

2022-11-22 03:26 UTC, lichnost commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/driver/multibase/fetch/base/BasePlainTableFetcher.java
>      @SuppressWarnings("unused")
@SuppressWarnings("unused") можно убрать

2022-11-22 03:26 UTC, lichnost commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/driver/multibase/fetch/base/BasePlainTableFetcher.java
> +    //private static Logger _log = LogManager.getLogger(BasePlainTableFetcher.class.getName());
Лишний коментарий.

2022-11-22 03:26 UTC, lichnost commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/driver/multibase/fetch/base/BasePlainTableFetcher.java
> +//import org.apache.logging.log4j.Logger;
Лишние коментарии

2022-11-22 03:26 UTC, lichnost commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/log/ContextPathInitializer.java
>  //	}
Этот класс больше не нужен. + нужно убрать его egjvbyfybt везде, в web.xml скорее всего будет.

2022-11-22 03:26 UTC, lichnost commented on pom.xml
> -            <!-- Logging -->
В блок dependencyManagment надо перенести зависимости с log4j2

2022-11-22 03:26 UTC, lichnost commented on whirl-app/whirl-app-server/pom.xml
> +            <version>2.4.1</version>
Убрать версию, она будет объявлена в dependencyManagement.

2022-11-22 03:26 UTC, lichnost commented on whirl-app/whirl-app-server/pom.xml
> +            <version>2.4.1</version>
Убрать версию, она будет объявлена в dependencyManagement.

2022-11-22 03:26 UTC, lichnost commented on whirl-editor/whirl-editor-server/pom.xml
> +            <version>2.4.1</version>
Убрать версию, она будет объявлена в dependencyManagement.

2022-11-22 03:26 UTC, lichnost commented on whirl-editor/whirl-editor-server/pom.xml
> +            <version>2.4.1</version>
Убрать версию, она будет объявлена в dependencyManagement.

2022-11-22 03:26 UTC, lichnost commented
ContextPathInitializer совсем убрать надо, плюс его упоминания везде тоже, скорее всего будет в web.xml.

2022-11-23 14:09 UTC, VladWick commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/driver/multibase/fetch/base/BasePlainTableFetcher.java
>      @SuppressWarnings("unused")
Убрал

2022-11-23 14:09 UTC, VladWick commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/driver/multibase/fetch/base/BasePlainTableFetcher.java
> +    //private static Logger _log = LogManager.getLogger(BasePlainTableFetcher.class.getName());
Убрал

2022-11-23 14:09 UTC, VladWick commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/driver/multibase/fetch/base/BasePlainTableFetcher.java
> +//import org.apache.logging.log4j.Logger;
Убрал

2022-11-24 08:08 UTC, VladWick commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/driver/multibase/fetch/base/BasePlainTableFetcher.java
> +        _log.info("Hello LOGS! ::: " + selectCmd.getSelect());
Обновил

2022-11-24 08:12 UTC, VladWick commented on whirl-app/whirl-app-server/src/main/java/org/whirlplatform/server/log/ContextPathInitializer.java
>  //	}
Классы убрал, упоминания в web.xml не нашёл...

2022-11-24 08:15 UTC, VladWick commented on pom.xml
> -            <!-- Logging -->
А где этот блок находится ?

2022-11-24 12:11 UTC, lichnost commented on pom.xml
> -            <!-- Logging -->
В корновом pom.xml. https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#dependency-management

2022-11-24 21:39 UTC, VladWick commented on pom.xml
> -            <!-- Logging -->
Сделал

2022-11-24 21:40 UTC, VladWick commented on whirl-app/whirl-app-server/pom.xml
> +            <version>2.4.1</version>
Убрал

2022-11-24 21:40 UTC, VladWick commented on whirl-app/whirl-app-server/pom.xml
> +            <version>2.4.1</version>
Убрал

2022-11-24 21:40 UTC, VladWick commented on whirl-editor/whirl-editor-server/pom.xml
> +            <version>2.4.1</version>
Убрал

2022-11-24 21:40 UTC, VladWick commented on whirl-editor/whirl-editor-server/pom.xml
> +            <version>2.4.1</version>
Убрал

2022-11-25 08:31 UTC, lichnost commented
Сюда заехала ветка со сборкой whirl-jsdoc/target почему-то - выпиливай.

2022-12-06 10:38 UTC, closed without merging